php8 compatibility
10up/autoshare-for-twitter pull request #144
Opened 2022-02-18 13:51 UTC by Sidsector9

### Description of the Change

Closes #

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

### Credits

Props @

2022-03-25 03:47 UTC, faisal-alvi commented on README.md
> +![PHPUnit](https://github.com/sidsector9/autoshare-for-twitter/actions/workflows/phpunit.yml/badge.svg)
The paths are coming from the forked repo. Can you please change it?

2022-03-25 03:49 UTC, faisal-alvi requested changes
Looks good, just a minor request added above.

2022-04-01 11:15 UTC, faisal-alvi requested changes
@Sidsector9 Code LGTM! However, I noticed,

1. A "PHP Compatibility" Github Action is failing.
2. The "test_php" tests are still in waiting mode. The wait is from Github and not in our control? or do we have to change something?

![image](https://user-images.githubusercontent.com/25176325/161252270-8e026f85-0d3b-48e3-b6a8-f23588fe36ea.png)
[image link](https://www.screencast.com/t/X4pehh7IL)

2022-04-07 06:24 UTC, faisal-alvi submitted a review, later dismissed

2022-04-08 04:21 UTC, iamdharmesh approved these changes

2022-04-08 04:21 UTC, merged