Added paths filter to GitHub actions
10up/autoshare-for-twitter pull request #204
Opened 2022-11-30 11:19 UTC by iamdharmesh

### Description of the Change

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/10up/.github/blob/trunk/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2022-12-01 02:39 UTC, peterwilsoncc approved these changes, later dismissed
Fake approval to see what happens.

2022-12-01 02:41 UTC, peterwilsoncc approved these changes, later dismissed
Another fake approval to test things now that develop has been merged in.

2022-12-01 02:45 UTC, peterwilsoncc requested changes
Sorry for the review spam while I was testing the effects of this PR.

In its current state, it prevents merging of approved PRs as the required actions have not completed.

I think what you'll want to do is something like this (pseudo code)

```yaml
step:
  Name: Succeed early if files are not modified
  run: |
    if ( no_relevant_file_modified() ) {
      finish_action_with_success();
    }
```

I'm not sure if that is possible though, it's something you'll need to check in the docs.

![Screen Shot 2022-12-01 at 1 41 46 pm](https://user-images.githubusercontent.com/519727/204953366-75f9dfea-56d5-46fc-948f-6c5aa4738679.png)

2022-12-01 10:15 UTC, iamdharmesh commented
@peterwilsoncc we can handle this by adding a generic workflow that ignores the path we added to the actual workflow So, it will run instead of the actual workflow and we can satisfy the `required` condition. More info can be found [here](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks)

I have created and added that workflow for PHPCS([c4d298d](https://github.com/10up/autoshare-for-twitter/pull/204/commits/c4d298dade8f3527dbe9cfd9752544df38cdadfe)) and it works as expected. what do you think about this approach? If you think adding an additional dummy workflow for each required workflow is additional overhead then we might can path filter only on heavy workflows like E2E tests OR adjust required workflow settings.

Thanks
cc: @dkotter

2022-12-01 23:21 UTC, peterwilsoncc commented
Thank @iamdharmesh -- that looks like a really nice approach. 

It does require repeating the paths in two files, so would need comments to alert people to change them in both locations. You could use a constant but I think that for two instances that would be over-engineering.

2022-12-04 23:07 UTC, peterwilsoncc approved these changes, later dismissed
LGTM with a minor nitpick inline.

I tested the changes with #209 to ensure that the tests run and fail as expected when needed.

2022-12-04 23:07 UTC, peterwilsoncc commented on .github/workflows/ignore-eslint.yml
> +      - run: 'echo "No ESLint check required"'
Nit: EOF line break would be lovely.

2022-12-04 23:07 UTC, peterwilsoncc commented on .github/workflows/ignore-phpunit.yml
> +      - run: 'echo "No PHPUnit check required"'
```suggestion
      - run: 'echo "No PHPUnit check required"'

```

Nit: EOF line break would be lovely

2022-12-07 21:35 UTC, peterwilsoncc approved these changes
Thank you! LGTM.

2022-12-08 04:17 UTC, merged