Update: Installation and setup
10up/autoshare-for-twitter pull request #78
Opened 2020-02-04 14:10 UTC by dinhtungdu

### Description of the Change

### Alternate Designs

### Benefits

### Possible Drawbacks

### Verification Process

### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Applicable Issues

### Changelog Entry

2020-02-05 17:35 UTC, jeffpaul commented on includes/admin/settings.php
> +			__( '<a href="%s">Setup your Twitter account</a>', 'autoshare-for-twitter' ),
Split `Setup` into `Set up`

2020-02-05 17:41 UTC, jeffpaul commented on includes/admin/settings.php
> +			</div>
Let's also include a link for `Support` underneath this line that links out to https://github.com/10up/autoshare-for-twitter/issues

2020-02-05 18:47 UTC, jeffpaul commented
Let's update the initial set up flow to be more like https://user-images.githubusercontent.com/2818133/70841275-c5669100-1dde-11ea-87de-36b212d411e6.png where we require folks to establish their connection to Twitter before getting into plugin-specific settings.  Once their connection to Twitter is setup, we can get into plugin settings like https://user-images.githubusercontent.com/2818133/70841299-ee872180-1dde-11ea-8229-763fc80f3b21.png and https://user-images.githubusercontent.com/2818133/70841348-73723b00-1ddf-11ea-90e3-fd0de332893f.png.  The following copy can be used for this initial settings page...

# Autoshare for Twitter settings

## Twitter connection settings

### 1. [Apply for a Twitter developer account](https://developer.twitter.com/en/apply/user.html)

### 2. Create a Twitter app for your website

- Click the `Create an app` button on the [Twitter develop apps page](https://developer.twitter.com/en/apps).
- Fill out the `App name` and `Application description` fields.
- Set the `Website URL` and `Callback URLs` fields to **https://yourdomain.yourdomainextension**.
- Fill out the `Tell us how this app will be used` field, no other fields or URLs are required or necessary.

### 3. Configure access to your Twitter app's API keys

- Click on the `Keys and tokens` tab within your newly created Twitter developer app.
- Copy the `API key` and `API secret key` values from your Twitter app `Consumer API keys` section and paste them below.
API key [`paste your API key here`]
API secret key [`paste your API secret key here`]

### 4. Configure access to your Twitter app's access tokens

- Click on the `Generate` button from your Twitter app `Access token & access token secret` section.
- Copy the `Access token` and `Access token secret` values and paste them below.
Access token [`paste your Access token here`]
Access token secret [`paste your Access token secret here`]

### 5. Confirm Twitter handle

- Fill out your Twitter handle that will be used to tweet your posts, pages, etc.
Twitter handle [`enter your Twitter handle here`]

### 6. Connect your Twitter developer app with this site

- Click the `Connect to Twitter` button below 🎉 
[`Connect to Twitter`]

2020-02-05 20:25 UTC, jeffpaul commented
After someone clicks the `Connect to Twitter` button from the initial plugin settings, the plugin settings page should save those details / connect to Twitter, and redirect to the post-Twitter connection settings/Autoshare settings version of the plugin settings page like https://user-images.githubusercontent.com/2818133/70841299-ee872180-1dde-11ea-8229-763fc80f3b21.png.  The following copy can be used for this initial settings page...

# Autoshare for Twitter settings

## Tweet settings

Enable Autoshare for:
(*) All content types <-- this should be our default
( ) Selected content types only
[ ] Posts
[ ] Pages
[ ] <CPT Name>  <-- we'll want to include checkboxes for any CPTs registered on the site

[x] Enable Autoshare by default when publishing content   <-- enabled by default
[x] Add featured image to the tweet by default   <-- enabled by default

## Twitter connection settings

*Open connection settings \\/*  <-- clicking this expands to show the full Twitter connection settings as described in the comment above and like https://user-images.githubusercontent.com/2818133/70841348-73723b00-1ddf-11ea-90e3-fd0de332893f.png

[`Update settings`]

2020-02-06 01:11 UTC, dinhtungdu commented
> (*) All content types <-- this should be our default

I think we should keep the current behavior of our plugin that supports only `post` and `page` by default.

> [ ] <-- we'll want to include checkboxes for any CPTs registered on the site

Yes, I include all custom post types to the post type checkbox. Also, if any post type is enabled using code, the checkbox will be checked and disabled.

2020-02-11 21:29 UTC, jeffpaul commented
@dinhtungdu 

> (*) All content types <-- this should be our default

> I think we should keep the current behavior of our plugin that supports only post and page by default.

Seems good, agreed.

2020-02-13 17:52 UTC, jeffpaul commented on includes/admin/settings.php
> +					<a href="https://github.com/10up/autoshare-for-twitter#faq" target="_blank" title="<?php echo esc_attr__( 'FAQ', 'autoshare-for-twitter' ); ?>">
Current link is plural "faqs"

2020-02-13 17:53 UTC, jeffpaul commented on includes/admin/settings.php
> +					<a href="https://github.com/10up/autoshare-for-twitter#installation" target="_blank" title="<?php echo esc_attr__( 'Installation & Set up', 'autoshare-for-twitter' ); ?>">
Probably can remove this link as the plugin is already installed and we're adding set up instructions via this PR

2020-02-13 20:01 UTC, jeffpaul commented
@dinhtungdu some UI updates for you...
- [ ] please update the settings page title from `Autoshare for Twitter` to `Autoshare for Twitter Settings`
- [ ] please update from double quotes "" around items to `preformatted text/code` format
- [ ] update yourdomain.yourdomainextension to **https://yourdomain.yourdomainextension**
- [ ] move the `API key` and `API secret key` labels+fields up into section 3
- [ ] add `paste your API key here` as helper text in the `API key` field
- [ ] add `paste your API secret key here` as helper text in the `API secret key` field
- [ ] remove duplicate section 3
- [ ] move the `Access token` and `Access token secret` labels+fields up into section 4
- [ ] add `paste your Access token here` as helper text in the `Access token` field
- [ ] add `paste your Access token secret here` as helper text in the `Access token secret` field
- [ ] move the `Twitter handle` and `https://twitter.com/` labels+field up into section 5
- [ ] add `enter your Twitter handle here` as helper text in the `Twitter handle` field
- [ ] on initial settings connection, have the button label be `Connect to Twitter` and not `Save Changes`
- [ ] after connecting to Twitter, ensure the `Selected content types only` radio button is selected by default (right now nothing is selected by default)
- [ ] change link label to `Open connection settings` from `Open credentials settings`
- [ ] when the connection settings are expanded, we'll want to continue displaying the 1-6 steps
- [ ] after connecting to Twitter, have the button label be `Update Settings` instead of `Save Changes`
- [ ] I'm starting to think we don't need the `Enable Autoshare by default when publishing content` setting because I don't think we have a toggle on/off in the content publishing workflow so by nature if the plugin is active then autoshare is enabled; if you agree, then let's remove that setting (as I don't know that it's tied to any action in the plugin currently)
- [ ] change `Upload featured image` to `Image setting`
- [ ] change ` Add featured image to the tweet by default` to `Always add the featured image to tweets`

Let me know if any of these are confusing or need further explanation, thanks!

2020-02-14 02:18 UTC, jeffpaul commented
After chatting with @dinhtungdu, we decided to strike the moving fields and button label changes as too hacky and not a simple solution that otherwise our plugin does a good job of staying simple.

2020-02-14 02:20 UTC, jeffpaul commented
Also noting from our discussion that it makes sense to keep the `Enable by default` setting, so we struck that from the UI change list as well.

2020-02-27 04:57 UTC, jeffpaul commented on includes/admin/settings.php
> +				<li><?php echo wp_kses_data( __( 'Click the <code>Create an app</code> button on the', 'autoshare-for-twitter' ) ); ?> <a href="https://developer.twitter.com/en/apps" title="<?php esc_html_e( 'Tw
Please update `develop` to `developer`.

2020-02-27 05:01 UTC, jeffpaul commented on includes/admin/settings.php
>  	// Access Secret.
Please update the field label from `Access secret` to `Access token secret`.

2020-02-27 05:02 UTC, jeffpaul commented on includes/admin/settings.php
> +				<li><?php echo wp_kses_data( __( 'Click the <code>Connect to Twitter</code> button below.', 'autoshare-for-twitter' ) ); ?></li>
The button label is `Save Changes` so if we're not able to change that to `Connect to Twitter` then please change the description here from `Connect to Twitter` to `Save Changes`.

2020-02-27 05:09 UTC, jeffpaul commented
1. When first navigating into the settings screen, are we able to hide / not show the `Close connection settings ^` link?  That would be ideal as a new user will need to complete these steps for Autoshare to work.  After they complete those fields and click `Save Changes`, then the `Open connection settings \/` and `Close connection settings ^` links make sense.

1. Please update the settings page title from `Autoshare for Twitter` to `Autoshare for Twitter Settings`.

2020-03-01 14:00 UTC, dinhtungdu commented
@jeffpaul Thanks for your reviews, I addressed your comments, please take another look!

2020-03-04 22:09 UTC, jeffpaul commented
Nice work @dinhtungdu, looks good to me.  Would be ideal to get a quick CR from @johnwatkins0 before merging.

2020-03-04 22:11 UTC, johnwatkins0 commented
I'll take a look and do some quick QA as well.

2020-03-05 03:33 UTC, johnwatkins0 requested changes
This is looking great and works well in my testing. Left a few comments, but all little things.

2020-03-05 04:28 UTC, dinhtungdu commented on assets/js/admin-autoshare-for-twitter-settings.js
> +	function getClosest( el, selector ) {
Ops, forgot to delete it after changing the logic

2020-03-05 04:42 UTC, dinhtungdu commented on includes/admin/settings.php
> +			<a href="JavaScript:void(0);" class="open">
because I want the markup match with the visual, see: https://prnt.sc/rbsj5t

2020-03-05 04:42 UTC, dinhtungdu commented
@johnwatkins0 Thanks for your detailed review! This PR is ready to review again.

2020-03-05 13:12 UTC, johnwatkins0 approved these changes
Looks good!

2020-03-06 21:04 UTC, merged